# config.yaml
flows:
  - observedWallet/*
  - send/*
  - settings/*
  - contactManagement/contactManagement.yaml
  - contactManagement/addContactsToScroll.yaml
  - tokenManagement/tokenManagement.yaml
  - onboarding/*
  - userActivity/userActivity.yaml
  - universal_link/*